# Generated by Django 4.1.2 on 2022-10-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightname', models.CharField(max_length=50)),
                ('flightnumber', models.IntegerField()),
                ('flightcapacity', models.IntegerField()),
                ('flightclass', models.CharField(max_length=50)),
            ],
        ),
    ]
