# Generated by Django 4.1.2 on 2022-10-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightreservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('passengercount', models.IntegerField()),
                ('ticketprice', models.IntegerField()),
                ('departuredate', models.DateField()),
                ('arrivaldate', models.DateField()),
                ('flightclass', models.CharField(max_length=50)),
            ],
        ),
    ]
